# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d64c4004788571e7e4534976acf1036b6f22a466218276642758420a75a78910df891f70f5ee91105d29d97c7c8566e5472f0cea1840562e974b46c603eaee

test:
  secret_key_base: aadc66de490f84e828c25ac3ab4f04f250d4d3cea52090ed900f62f0773cfe5bad4ae2790a2fafbd1771b27bb5411499f99730e513e2cac8e3cf755acaeadaad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
